app/advanced_htmx/urls.py
from django.urls import path

from advanced_htmx.ajax import CarCreateAjax
from advanced_htmx.ajax import ChatAjax
from advanced_htmx.ajax import RandomProductAjax
from advanced_htmx.ajax import RandomProductEventAjax
from advanced_htmx.ajax import TableProductsListAjax
from advanced_htmx.views import CarCreateView
from advanced_htmx.views import ChatView
from advanced_htmx.views import TableView

app_name = "advanced-htmx"
urlpatterns = [
    # Ajax
    path("ajax/products", TableProductsListAjax.as_view(), name="table-products-list-ajax"),
    path("ajax/product/random", RandomProductAjax.as_view(), name="product-random-ajax"),
    path("ajax/product/random/event", RandomProductEventAjax.as_view(), name="product-random-event-ajax"),
    path("ajax/car", CarCreateAjax.as_view(), name="car-create-ajax"),
    path("ajax/chat", ChatAjax.as_view(), name="chat-ajax"),
    # Views
    path("", TableView.as_view(), name="table"),
    path("car", CarCreateView.as_view(), name="car-create"),
    path("chat", ChatView.as_view(), name="chat"),
]

app/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

app_name = "myproject"
urlpatterns = [
    # Admin
    path("admin/", admin.site.urls),
    # Apps
    # todo_tracker
    path("", include("todo_tracker.urls", namespace="todo-tracker")),
    # advanced_htmx
    path("advanced/", include("advanced_htmx.urls", namespace="advanced-htmx")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/todo_tracker/urls.py
from django.urls import path

from todo_tracker.ajax.todo_list import AjaxTaskCreateView
from todo_tracker.ajax.todo_list import AjaxTaskDeleteView
from todo_tracker.views.todo_list import TodoListView

app_name = "todo-tracker"
urlpatterns = [
    path("", TodoListView.as_view(), name="todo-list"),
    # Ajax views
    path("ajax/todo-list", AjaxTaskCreateView.as_view(), name="ajax-task-create"),
    path("ajax/todo-list/<int:task_id>", AjaxTaskDeleteView.as_view(), name="ajax-task-delete"),
]

app/advanced_htmx/models.py
from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _


class ColorChoices(models.TextChoices):
    WHITE = "White", _("White")
    SILVER = "Silver", _("Silver")
    YELLOW = "Yellow", _("Yellow")
    BLUE = "Blue", _("Blue")
    RED = "Red", _("Red")
    GREEN = "Green", _("Green")
    BLACK = "Black", _("Black")
    OTHER = "Other", _("Other")


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True, blank=False, null=False)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, unique=True, blank=False, null=False)
    color = models.CharField(
        max_length=10,
        choices=ColorChoices.choices,
        default=ColorChoices.OTHER.value,
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class Car(models.Model):
    name = models.CharField(max_length=255, unique=True, blank=False, null=False)
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal("0.00"))],
    )
    photo = models.ImageField(upload_to="cars")

    def __str__(self):
        return self.name

app/todo_tracker/models.py
from django.db import models


class Task(models.Model):
    value = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.value

app/advanced_htmx/forms.py
from django import forms


class ChatMessageForm(forms.Form):
    signature = forms.CharField()
    text = forms.CharField()

app/advanced_htmx/views.py
from typing import Any
from typing import Dict

from django.views.generic import TemplateView
from django.views.generic.list import ListView

from advanced_htmx.handlers import ChatHandler
from advanced_htmx.models import Product


class TableView(ListView):
    model = Product
    template_name = "advanced_htmx/table.html"

    paginate_by = 10
    queryset = Product.objects.select_related("category").order_by("id")


class CarCreateView(TemplateView):
    template_name = "advanced_htmx/car_create.html"


class ChatView(TemplateView):
    template_name = "advanced_htmx/chat.html"

    def get_context_data(self, *args, **kwargs):
        ctx: Dict[str, Any] = super().get_context_data(*args, **kwargs)
        ctx["messages"] = ChatHandler.get_messages_data()

        return ctx

app/todo_tracker/views/todo_list.py
from django.views.generic.list import ListView

from todo_tracker.models import Task


class TodoListView(ListView):
    model = Task
    template_name = "todo_list.html"

    paginate_by = 25
    queryset = Task.objects.order_by("-created_at")

app/core/templates/advanced_htmx/mini_partials/product_random.html
<p
  hx-get="{% url 'advanced-htmx:product-random-ajax' %}"
  {% if request.headers.hx_request %}
    hx-trigger="load delay:1s"
  {% else %}
    hx-trigger="load delay:3s"
  {% endif %}
  hx-swap="outerHTML"
  class="m-2 font-semibold text-gray-950"
>
  Random product every 1s:
  {% if random_product %}
    {{ random_product }}
  {% else %}
    <img class="inline w-8" src="https://htmx.org/img/bars.svg" alt="Result loading..."/>
  {% endif%}
</p>

app/core/templates/advanced_htmx/partials/table_footer.html
<footer class="container mx-auto bg-white rounded-lg shadow m-4 dark:bg-gray-800">
  <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">
      Advanced HTMX
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0">
      <li>
        <a href="#" class="mr-4 hover:underline md:mr-6">About</a>
      </li>
      <li>
        <a href="#" class="mr-4 hover:underline md:mr-6">Privacy Policy</a>
      </li>
      <li>
        <a href="#" class="mr-4 hover:underline md:mr-6">Licensing</a>
      </li>
      <li>
        <a href="#" class="hover:underline">Contact</a>
      </li>
    </ul>
  </div>
</footer>

app/core/templates/advanced_htmx/partials/table_products_list.html
<main id="table-products-list" class="m-4 transition-all">
  <div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-500">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3">Product name</th>
          <th scope="col" class="px-6 py-3">Color</th>
          <th scope="col" class="px-6 py-3">Category</th>
          <th scope="col" class="px-6 py-3">Price</th>
        </tr>
      </thead>
      <tbody>
        {% for product in object_list %}
          {% include "advanced_htmx/partials/table_product_item.html" %}
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="flex flex-col items-center">
    {% if page_obj.has_next or page_obj.has_previous %}
      <div class="inline-flex mt-2 xs:mt-0">
        {% if page_obj.has_previous %}
          <a
            hx-get="{% url 'advanced-htmx:table-products-list-ajax' %}?page={{ page_obj.previous_page_number }}"
            hx-target="#table-products-list"
            hx-swap="outerHTML swap:50ms"
            hx-disabled-elt="this"
            {% if page_obj.previous_page_number > 1 %}
                hx-replace-url="{% url 'advanced-htmx:table' %}?page={{ page_obj.previous_page_number }}"
            {% else %}
                hx-replace-url="{% url 'advanced-htmx:table' %}"
            {% endif %}
            href="#"
            class="flex items-center justify-center px-4 h-10 mr-3 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700"
          >
            Previous
          </a>
        {% endif %}
        {% if page_obj.has_next %}
          <a
            hx-get="{% url 'advanced-htmx:table-products-list-ajax' %}?page={{ page_obj.next_page_number }}"
            hx-target="#table-products-list"
            hx-swap="outerHTML swap:50ms"
            hx-disabled-elt="this"
            hx-replace-url="{% url 'advanced-htmx:table' %}?page={{ page_obj.next_page_number }}"
            href="#"
            class="flex items-center justify-center px-4 h-10 mr-3 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700"
          >
            Next
          </a>
        {% endif %}
      </div>
    {% endif %}
  </div>
</main>

{% if request.headers.hx_request %}
  <span id="products-list-counter" hx-swap-oob="true">{{ page_obj.number }}</span>
{% endif %}

app/templates/advanced_htmx/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="htmx-config" content='{"includeIndicatorStyles": false}'>

    <title>{% block title %}Example Web page{% endblock title %}</title>

    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/tailwind-output.css' %}">

    <script src="{% static 'js/htmx.min.js' %}"></script>
    <script src="{% static 'js/flowbite.min.js' %}"></script>

    {% block head_extra %}{% endblock head_extra %}
  </head>
  <body class="container mx-auto" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    {% include "advanced_htmx/partials/header.html" %}
    {% block content %}{% endblock content %}
    {% include "advanced_htmx/partials/footer.html" %}
  </body>
</html>

app/templates/advanced_htmx/car_create.html
{% extends "advanced_htmx/base.html" %}
{% load static %}

{% block head_extra %}
  <link rel="stylesheet" href="{% static 'css/table.css' %}" />
{% endblock head_extra %}

{% block content %}
  {% include "advanced_htmx/partials/car_create.html" %}
{% endblock content %}

app/templates/advanced_htmx/chat.html
{% extends "advanced_htmx/base.html" %}
{% load static %}

{% block head_extra %}
  <script src="{% static 'js/htmx_ext_ws.js' %}"></script>
{% endblock head_extra %}

{% block content %}
  <main class="m-4">
    {% include "advanced_htmx/mini_partials/chat_messages_container.html" %}
    {% include "advanced_htmx/partials/chat_messages_form.html" %}
  </main>
{% endblock content %}

app/templates/advanced_htmx/mini_partials/car_create_form_field.html
<div class="mb-6">
  <label for="{{ label_for }}" class="block mb-2 text-sm font-medium text-gray-900">{{ label }}</label>
  <input
    {% if input_type %}type="{{ input_type }}"{% endif %}
    {% if input_id %}id="{{ input_id }}"{% endif %}
    {% if input_name %}name="{{ input_name }}"{% endif %}
    {% if input_class %}
      class="{{ input_class }}"
    {% else %}
      class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
    {% endif %}
    {% if input_placeholder %}placeholder="{{ input_placeholder }}"{% endif %}
    {% if input_value %}value="{{ input_value }}"{% endif %}
    {% if input_step %}step="{{ input_step }}"{% endif %}
    {% if input_required %}required{% endif %}
  />
  {% if errors %}
    {% for error in errors %}
      <p class="mt-2 text-sm text-red-600">
        {{ error }}
      </p>
    {% endfor %}
  {% endif %}
</div>

app/templates/advanced_htmx/mini_partials/chat_messages_container.html
<div
  id="chat-messages-container"
  hx-ext="ws"
  ws-connect="/ws/chatroom"
  hx-swap-oob="beforeend"
  class="m-4"
>
  {% for msg in messages %}
    <div
      class="flex items-center w-full max-w-xs mb-3 p-4 text-gray-500 bg-white rounded-lg shadow"
      role="alert"
    >
      <div class="ml-3 text-sm font-normal"><span class="font-semibold">{{ msg.signature }}: </span>{{ msg.text }}</div>
    </div>
  {% endfor %}
</div>

app/templates/advanced_htmx/mini_partials/product_random.html
<p
  hx-get="{% url 'advanced-htmx:product-random-ajax' %}"
  {% if request.headers.hx_request %}
    hx-trigger="load delay:10s"
  {% else %}
    hx-trigger="load delay:3s"
  {% endif %}
  hx-swap="outerHTML"
  class="m-2 font-semibold text-gray-950"
>
  Random product every 10s:
  {% if random_product %}
    {{ random_product }}
  {% else %}
    <img class="inline w-8" src="https://htmx.org/img/bars.svg" alt="Result loading..."/>
  {% endif%}
</p>

app/templates/advanced_htmx/mini_partials/product_random_event.html
<p
  hx-get="{% url 'advanced-htmx:product-random-event-ajax' %}"
  {% if request.headers.hx_request %}
    hx-trigger="{{ htmx_triggers.products_list_page_changed }} from:body"
  {% else %}
    hx-trigger="load delay:2.5s"
  {% endif %}
  hx-swap="outerHTML"
  class="m-2 font-semibold text-gray-950"
>
  Random product when custom event(changed page):
  {% if random_product %}
    {{ random_product }}
  {% else %}
    <img class="inline w-8" src="https://htmx.org/img/bars.svg" alt="Result loading..."/>
  {% endif %}
</p>

app/templates/advanced_htmx/mini_partials/products_counter.html
<p class="m-2 font-semibold text-gray-950">
  Out of Band Element - Current Page: <span id="products-list-counter">{{ page_number }}</span>
</p>

app/templates/advanced_htmx/partials/car_create.html
<form
  class="m-4"
  hx-post="{% url 'advanced-htmx:car-create-ajax' %}"
  hx-swap="outerHTML"
  hx-encoding="multipart/form-data"
>
  {% comment %} Car name field {% endcomment %}
  {% include "advanced_htmx/mini_partials/car_create_form_field.html" with label_for="name" label="Car name" input_type="text" input_id="name" input_name="name" input_placeholder="Car" input_value=form.name.value input_required="true" errors=form.errors.name %}
  {% comment %} Car price field {% endcomment %}
  {% include "advanced_htmx/mini_partials/car_create_form_field.html" with label_for="price" label="Car price" input_type="number" input_id="price" input_name="price" input_value=form.price.value input_step=".01" input_required="true" errors=form.errors.price %}
  {% comment %} Car photo field {% endcomment %}
  {% include "advanced_htmx/mini_partials/car_create_form_field.html" with label_for="photo" label="Car photo" input_type="file" input_id="photo" input_name="photo" input_class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50focus:outline-none" errors=form.errors.photo %}
  <button
    type="submit"
    class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"
  >
    Submit
  </button>
</form>

app/templates/advanced_htmx/partials/chat_messages_form.html
<form
  id="chat-form"
  hx-post="{% url 'advanced-htmx:chat-ajax' %}"
  hx-on::after-request="this.text.value = ''"
  hx-swap="outerHTML"
>
  <div class="flex items-center px-3 py-2 rounded-lg bg-gray-50">
    <label for="text" class="sr-only">Your message</label>
    <input
      type="text"
      id="text"
      name="text"
      rows="1"
      class="block mx-4 p-2.5 w-full text-sm text-gray-900 bg-white rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500"
      placeholder="Your message..."
      autocomplete="off"
      required
    ></input>
    <button
      type="submit"
      class="inline-flex justify-center p-2 text-blue-600 rounded-full cursor-pointer hover:bg-blue-100"
    >
      <svg
        class="w-5 h-5 rotate-90"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        fill="currentColor"
        viewBox="0 0 18 20"
      >
        <path
          d="m17.914 18.594-8-18a1 1 0 0 0-1.828 0l-8 18a1 1 0 0 0 1.157 1.376L8 18.281V9a1 1 0 0 1 2 0v9.281l6.758 1.689a1 1 0 0 0 1.156-1.376Z"
        />
      </svg>
      <span class="sr-only">Send message</span>
    </button>
  </div>
  <div class="flex items-center px-3 py-2 rounded-lg bg-gray-50">
    <label for="signature" class="block m-2 text-sm font-medium text-gray-900">Signature</label>
    <input
      type="text"
      name="signature"
      id="signature"
      class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
      placeholder="John"
      autocomplete="off"
      required
    />
  </div>
</form>

app/templates/advanced_htmx/partials/footer.html
<footer class="bg-white rounded-lg shadow m-4">
  <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
    <span class="text-sm text-gray-500 sm:text-center">
      Advanced HTMX
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 sm:mt-0">
      <li>
        <a href="{% url 'advanced-htmx:table' %}" class="mr-4 hover:underline md:mr-6">Table</a>
      </li>
      <li>
        <a href="{% url 'advanced-htmx:car-create' %}" class="mr-4 hover:underline md:mr-6">Car Create</a>
      </li>
      <li>
        <a href="{% url 'advanced-htmx:chat' %}" class="mr-4 hover:underline md:mr-6">Chat</a>
      </li>
    </ul>
  </div>
</footer>

app/templates/advanced_htmx/partials/header.html
<header>
  <nav class="bg-white border-gray-200">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between m-4 p-4">
      <a href="{% url 'advanced-htmx:table' %}" class="flex items-center">
        <span class="self-center text-2xl font-semibold whitespace-nowrap">Advanced HTMX</span>
      </a>
      <button
        data-collapse-toggle="navbar-default"
        type="button"
        class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200"
        aria-controls="navbar-default"
        aria-expanded="false"
      >
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
          <path
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M1 1h15M1 7h15M1 13h15"
          />
        </svg>
      </button>
      <div class="hidden w-full md:block md:w-auto" id="navbar-default">
        {% with current_page_styles='class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 aria-current="page"' default_page_styles='class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0"' %}
          <ul
            class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white"
          >
            <li>
              <a
                href="{% url 'advanced-htmx:table' %}"
                {% if request.resolver_match.url_name == "table" %}
                  {{ current_page_styles }}
                {% else %}
                  {{ default_page_styles }}
                {% endif %}
                >Table</a
              >
            </li>
            <li>
              <a
                href="{% url 'advanced-htmx:car-create' %}"
                {% if request.resolver_match.url_name == "car-create" %}
                  {{ current_page_styles }}
                {% else %}
                  {{ default_page_styles }}
                {% endif %}
                >Car Create</a
              >
            </li>
            <li>
              <a
                href="{% url 'advanced-htmx:chat' %}"
                {% if request.resolver_match.url_name == "chat" %}
                  {{ current_page_styles }}
                {% else %}
                  {{ default_page_styles }}
                {% endif %}
                >Chat</a
              >
            </li>
          </ul>
        {% endwith %}
      </div>
    </div>
  </nav>
</header>

app/templates/advanced_htmx/partials/table_products_list.html
<main id="table-products-list" class="m-4 transition-all">
  <div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-500">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3">Product name</th>
          <th scope="col" class="px-6 py-3">Color</th>
          <th scope="col" class="px-6 py-3">Category</th>
          <th scope="col" class="px-6 py-3">Price</th>
        </tr>
      </thead>
      <tbody>
        {% if object_list %}
          {% for product in object_list %}
            {% include "advanced_htmx/partials/table_product_item.html" %}
          {% endfor %}
        {% else %}
          <tr class="bg-white border-b">
            <th colspan="4" scope="row" class="text-center px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
              <p class="text-xl italic font-semibold text-gray-900 dark:text-white">
                Nothing to show here. Go to the
                <a
                  class="font-medium text-blue-600 dark:text-blue-500 hover:underline"
                  href="http://localhost:8000/admin/advanced_htmx/product/"
                  >admin panel</a
                >
                and add some products
              </p>
            </th>
          </tr>
        {% endif %}
      </tbody>
    </table>
  </div>

  <div class="flex flex-col items-center">
    {% if page_obj.has_next or page_obj.has_previous %}
      <div class="inline-flex mt-2 xs:mt-0">
        {% if page_obj.has_previous %}
          <a
            hx-get="{% url 'advanced-htmx:table-products-list-ajax' %}?page={{ page_obj.previous_page_number }}"
            hx-target="#table-products-list"
            hx-swap="outerHTML swap:50ms"
            hx-disabled-elt="this"
            {% if page_obj.previous_page_number > 1 %}
                hx-replace-url="{% url 'advanced-htmx:table' %}?page={{ page_obj.previous_page_number }}"
            {% else %}
                hx-replace-url="{% url 'advanced-htmx:table' %}"
            {% endif %}
            href="#"
            class="flex items-center justify-center px-4 h-10 mr-3 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700"
          >
            Previous
          </a>
        {% endif %}
        {% if page_obj.has_next %}
          <a
            hx-get="{% url 'advanced-htmx:table-products-list-ajax' %}?page={{ page_obj.next_page_number }}"
            hx-target="#table-products-list"
            hx-swap="outerHTML swap:50ms"
            hx-disabled-elt="this"
            hx-replace-url="{% url 'advanced-htmx:table' %}?page={{ page_obj.next_page_number }}"
            href="#"
            class="flex items-center justify-center px-4 h-10 mr-3 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700"
          >
            Next
          </a>
        {% endif %}
      </div>
    {% endif %}
  </div>
</main>

{% if request.headers.hx_request %}
  <span id="products-list-counter" hx-swap-oob="true">{{ page_obj.number }}</span>
{% endif %}

app/templates/partials/task_item.html
<li class="mt-4" id="task-item-{{ task.id }}">
    <div class="flex gap-2">
        <div class="w-9/12 h-12 bg-orange-500 rounded-[7px] flex justify-start items-center px-3">
            <form
                id="check{{ task.id }}"
                hx-post="{% url "todo-tracker:ajax-task-delete" task_id=task.id %}"
                hx-target="#task-item-{{ task.id }}"
                hx-swap="delete"
                hx-trigger="click delay:300ms"
                class="w-7 h-7 bg-white rounded-full border border-white transition-all cursor-pointer hover:border-orange-200 flex justify-center items-center"
                onclick="checked({{ task.id }})"
            >
                <i class="text-white fa fa-check"></i>
            </form>
            <strike id="strike{{ task.id }}" class="strike_none text-sm ml-4 text-white font-semibold"
                >{{ task.value }}</strike
            >
        </div>
        <span
            class="w-1/4 h-12 p3 bg-orange-500 rounded-[7px] flex justify-center text-xs text-white font-semibold items-center"
            >{{ task.created_at|date:"g:i a" }}<br />{{ task.created_at|date:"d/m/Y" }}
        </span>
    </div>
</li>

app/templates/partials/tasks_list.html
<ul id="tasks-list" class="my-4">
    <li class="mt-4" id="6">
        <form class="flex gap-2" hx-post="{% url "todo-tracker:ajax-task-create" %}" hx-target="#tasks-list" hx-swap="outerHTML">
            <div class="w-9/12 h-12 bg-orange-500 rounded-[7px] flex justify-start items-center px-3">
                <input
                    name="value" type="text"
                    class="w-full p-1 text-orange-700 placeholder:text-slate-300 focus:outline-none focus-visible:ring-orange-300 font-semibold rounded-[7px]"
                    placeholder="Add new task"
                    autofocus
                    required
                />
            </div>
            <button
                class="w-1/4 h-12 bg-orange-500 hover:bg-orange-800 focus:ring-4 focus:ring-orange-300 rounded-[7px] flex justify-center text-sm text-white font-semibold items-center"
            >
                Add
            </button>
        </form>
    </li>
    {% for task in object_list %} {% include "partials/task_item.html" with task=task %} {% endfor %}
</ul>

app/templates/todo_list.html
{% extends "base.html" %}
{% load static%}

{% block head_extra %}
    <link rel="stylesheet" href="{% static 'css/todo_list.css' %}">
    <script src="{% static 'js/todo_list.js' %}"></script>
{% endblock head_extra %}
{% block content %}
    <div class="flex justify-center items-center min-h-screen bg-orange-50">
        <div class="h-auto  w-96 bg-white rounded-[20px] p-4">
            <div class="mt-3 text-sm text-orange-300 flex justify-between items-center">
                <p class="set_date">{% now "l d F" %}</p>
                <p class="set_time">{% now "h:i a" %}</p>
            </div>
            <p class="text-xl font-semibold mt-2 text-orange-700">To-do List</p>
            <div class="w-full mt-2 flex text-sm flex-col text-center justify-center ">
                <div class=" px-[15px] flex justify-between text-center items-center">
                    {% for day in days %}
                        <p>{{ day|date:"D" }}</p>
                    {% endfor %}
                </div>
                <div class="w-full pl-1 flex justify-between text-center items-center">
                    {% for day in days %}
                        <span class="h-7 w-7 rounded-full cursor-pointer transition-all hover:bg-orange-700 hover:text-white bg-white flex justify-center items-center"><p>{{ day|date:"d" }}</p></span>
                    {% endfor %}
                </div>
            </div>
            {% include "partials/tasks_list.html" with object_list=task_list %}
        </div>
    </div>
{% endblock content %}